/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: T-FLEX CAD ST (Free) (https://sketchfab.com/tflexcad)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/offroad-bumper-8a4c61ccd67e482ca56dd10614b18023
Title: Offroad Bumper
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../Bullbar/Bullbar1/scene.gltf')
  return (
    <group {...props} dispose={null} scale={13}>
      <group position={[-0.3, -0.74, 0.2]} rotation={[0, -1.35 , Math.PI]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.AppC5} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.AppC5} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.AppC5} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.AppC5} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.AppC5} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.App82} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.App82} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.App82} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.App82} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.App82} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.App82} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.App82} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.App82} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.App82} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.AppC5_0} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.AppC5_0} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.AppB3} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.App31} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
