/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 scene.gltf 
Author: baukepost (https://sketchfab.com/baukepost)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bumper-wip-cd8217044701437785564a5e54532888
Title: Bumper wip
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../Bumpers/Bumper1/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={props.position} scale={props.size} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material-color={props.updatecolor} geometry={nodes.Suzanne004_0.geometry} material={materials['Scene_-_Root']} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
