/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Blender Boy (https://sketchfab.com/Blender_Boy1)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/toyota-corolla-e170-2017-d87af59849814c5cb35a0c233f2c2f19
Title: toyota-corolla-e170-2017
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../Gli/scene.gltf')
  return (
    <group {...props} dispose={null} scale={5.5}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.144}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.767, 0.285, -1.28]}>
            <mesh geometry={nodes.Object_115.geometry} material={materials.e180_chrome} />
            <mesh geometry={nodes.Object_116.geometry} material={materials.e180_gray} />
          </group>
          <group position={[0.767, 0.285, -1.28]}>
            <mesh geometry={nodes.Object_270.geometry} material={materials.e180_black} />
            <mesh geometry={nodes.Object_271.geometry} material={materials.e180_red} />
            <mesh geometry={nodes.Object_272.geometry} material={materials.displaye180} />
          </group>
          <group position={[-0.767, 0.285, -1.28]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Object_276.geometry} material={materials.e180_chrome} />
            <mesh geometry={nodes.Object_277.geometry} material={materials.e180_gray} />
          </group>
          <group position={[-0.767, 0.285, -1.28]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Object_279.geometry} material={materials.e180_black} />
            <mesh geometry={nodes.Object_280.geometry} material={materials.e180_red} />
            <mesh geometry={nodes.Object_281.geometry} material={materials.displaye180} />
          </group>
          <group position={[0.767, 0.294, 1.31]}>
            <mesh geometry={nodes.Object_285.geometry} material={materials.e180_chrome} />
            <mesh geometry={nodes.Object_286.geometry} material={materials.e180_gray} />
          </group>
          <group position={[0.767, 0.294, 1.31]}>
            <mesh geometry={nodes.Object_288.geometry} material={materials.e180_black} />
            <mesh geometry={nodes.Object_289.geometry} material={materials.e180_red} />
            <mesh geometry={nodes.Object_290.geometry} material={materials.displaye180} />
          </group>
          <group position={[-0.767, 0.294, 1.31]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Object_294.geometry} material={materials.e180_chrome} />
            <mesh geometry={nodes.Object_295.geometry} material={materials.e180_gray} />
          </group>
          <group position={[-0.767, 0.294, 1.31]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Object_297.geometry} material={materials.e180_black} />
            <mesh geometry={nodes.Object_298.geometry} material={materials.e180_red} />
            <mesh geometry={nodes.Object_299.geometry} material={materials.displaye180} />
          </group>
          <mesh geometry={nodes.Object_4.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.e180_black} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.sunburst_engine} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.e180_glass} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.e180_glass} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.e180_glass} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.e180_glass_out} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.e180_glass} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.e180_glassred} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.e180_glass} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.e180_glassred} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.e180_glass} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.e180_glassred} />
          <mesh geometry={nodes.Object_27.geometry} material={materials.e180_glass_out} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.e180_glass_out} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.e180_glass_out} />
          <mesh geometry={nodes.Object_33.geometry} material={materials.e180_glass_out} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.e180_glass_out} />
          <mesh geometry={nodes.Object_36.geometry} material={materials.e180_povl} />
          <mesh geometry={nodes.Object_38.geometry} material={materials.e180_glass_out} />
          <mesh geometry={nodes.Object_39.geometry} material={materials.e180_povr} />
          <mesh geometry={nodes.Object_41.geometry} material={materials.e180_povr} />
          <mesh geometry={nodes.Object_42.geometry} material={materials.e180_red} />
          <mesh geometry={nodes.Object_44.geometry} material={materials.e180_povl} />
          <mesh geometry={nodes.Object_45.geometry} material={materials.e180_red} />
          <mesh geometry={nodes.Object_47.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_49.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_51.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_53.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_55.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_57.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_59.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_61.geometry} material={materials.e180body} />
          <mesh geometry={nodes.Object_63.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_65.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_67.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_69.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_71.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_73.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_75.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_77.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_79.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_81.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_83.geometry} material={materials.sunburst} position={[-0.767, 0.285, -1.28]} />
          <mesh geometry={nodes.Object_85.geometry} material={materials.sunburst} position={[0.767, 0.285, -1.28]} />
          <mesh geometry={nodes.Object_87.geometry} material={materials.sunburst} position={[-0.767, 0.294, 1.31]} />
          <mesh geometry={nodes.Object_89.geometry} material={materials.sunburst} position={[0.767, 0.294, 1.31]} />
          <mesh geometry={nodes.Object_91.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_93.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_95.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_97.geometry} material={materials.sunburst_gauges} position={[0.325, 2.192, 0.65]} rotation={[1.951, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_99.geometry} material={materials.sunburst_gauges} position={[0.423, 2.192, 0.65]} rotation={[1.951, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_101.geometry} material={materials.sunburst_gauges} position={[0.489, 2.151, 0.636]} rotation={[-1.239, 0, 0]} />
          <mesh geometry={nodes.Object_103.geometry} material={materials.sunburst_gauges} position={[0.542, 2.15, 0.636]} rotation={[1.928, 0.797, -Math.PI]} />
          <mesh geometry={nodes.Object_105.geometry} material={materials.sunburst_engine} />
          <mesh geometry={nodes.Object_107.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_109.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_111.geometry} material={materials.sunburst} />
          <mesh geometry={nodes.Object_113.geometry} material={materials.e180_black} position={[0.767, 0.285, -1.28]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_118.geometry} material={materials.e180_povl} />
          <mesh geometry={nodes.Object_119.geometry} material={materials.e180_chrome} />
          <mesh geometry={nodes.Object_120.geometry} material={materials.e180_gray} />
          <mesh geometry={nodes.Object_121.geometry} material={materials.e180_short} />
          <mesh geometry={nodes.Object_122.geometry} material={materials.e180_long} />
          <mesh geometry={nodes.Object_124.geometry} material={materials.e180_povr} />
          <mesh geometry={nodes.Object_125.geometry} material={materials.e180_lights} />
          <mesh geometry={nodes.Object_126.geometry} material={materials.e180_tails} />
          <mesh geometry={nodes.Object_128.geometry} material={materials.e180_glass_out} />
          <mesh geometry={nodes.Object_130.geometry} material={materials.e180_povl} />
          <mesh geometry={nodes.Object_131.geometry} material={materials.e180_lights} />
          <mesh geometry={nodes.Object_132.geometry} material={materials.e180_tails} />
          <mesh geometry={nodes.Object_134.geometry} material={materials.e180_povr} />
          <mesh geometry={nodes.Object_135.geometry} material={materials.e180_chrome} />
          <mesh geometry={nodes.Object_136.geometry} material={materials.e180_gray} />
          <mesh geometry={nodes.Object_137.geometry} material={materials.e180_short} />
          <mesh geometry={nodes.Object_138.geometry} material={materials.e180_long} />
          <mesh geometry={nodes.Object_140.geometry} material={materials.e180_black} />
          <mesh geometry={nodes.Object_141.geometry} material={materials.mirror} />
          <mesh geometry={nodes.Object_142.geometry} material={materials.e180body} />
          <mesh geometry={nodes.Object_143.geometry} material={materials.e180_povl} />
          <mesh geometry={nodes.Object_144.geometry} material={materials.e180_glass_out} />
          <mesh geometry={nodes.Object_146.geometry} material={materials.e180body} />
          <mesh geometry={nodes.Object_147.geometry} material={materials.e180_chrome} />
          <mesh geometry={nodes.Object_148.geometry} material={materials.e180_gray} />
          <mesh geometry={nodes.Object_149.geometry} material={materials.e180_interior} />
          <mesh geometry={nodes.Object_150.geometry} material={materials.e180_int} />
          <mesh geometry={nodes.Object_152.geometry} material={materials.e180_black} />
          <mesh geometry={nodes.Object_153.geometry} material={materials.e180_glass} />
          <mesh geometry={nodes.Object_154.geometry} material={materials.e180_glass_out} />
          <mesh geometry={nodes.Object_155.geometry} material={materials.e180_povr} />
          <mesh geometry={nodes.Object_156.geometry} material={materials.e180body} />
          <mesh geometry={nodes.Object_157.geometry} material={materials.mirror} />
          <mesh geometry={nodes.Object_159.geometry} material={materials.e180body} />
          <mesh geometry={nodes.Object_160.geometry} material={materials.e180_chrome} />
          <mesh geometry={nodes.Object_161.geometry} material={materials.e180_gray} />
          <mesh geometry={nodes.Object_162.geometry} material={materials.e180_interior} />
          <mesh geometry={nodes.Object_163.geometry} material={materials.e180_int} />
          <mesh geometry={nodes.Object_165.geometry} material={materials.e180body} />
          <mesh geometry={nodes.Object_166.geometry} material={materials.e180_chrome} />
          <mesh geometry={nodes.Object_167.geometry} material={materials.e180_gray} />
          <mesh geometry={nodes.Object_168.geometry} material={materials.e180_interior} />
          <mesh geometry={nodes.Object_169.geometry} material={materials.e180_int} />
          <mesh geometry={nodes.Object_171.geometry} material={materials.e180body} />
          <mesh geometry={nodes.Object_172.geometry} material={materials.e180_chrome} />
          <mesh geometry={nodes.Object_173.geometry} material={materials.e180_gray} />
          <mesh geometry={nodes.Object_174.geometry} material={materials.e180_interior} />
          <mesh geometry={nodes.Object_175.geometry} material={materials.e180_int} />
          <mesh geometry={nodes.Object_177.geometry} material={materials.e180_black} />
          <mesh geometry={nodes.Object_178.geometry} material={materials.e180body} />
          <mesh geometry={nodes.Object_180.geometry} material={materials.e180_black} />
          <mesh geometry={nodes.Object_181.geometry} material={materials.e180_red} />
          <mesh geometry={nodes.Object_182.geometry} material={materials.e180body} />
          <mesh geometry={nodes.Object_183.geometry} material={materials.e180_chrome} />
          <mesh geometry={nodes.Object_184.geometry} material={materials.e180_gray} />
          <mesh geometry={nodes.Object_185.geometry} material={materials.e180_lights} />
          <mesh geometry={nodes.Object_186.geometry} material={materials.e180_white} />
          <mesh geometry={nodes.Object_187.geometry} material={materials.e180_tail} />
          <mesh geometry={nodes.Object_188.geometry} material={materials.e180_RL} />
          <mesh geometry={nodes.Object_190.geometry} material={materials.e180_glass} />
          <mesh geometry={nodes.Object_191.geometry} material={materials.e180_glassred} />
          <mesh geometry={nodes.Object_192.geometry} material={materials.e180_red} />
          <mesh geometry={nodes.Object_193.geometry} material={materials.e180body} />
          <mesh geometry={nodes.Object_194.geometry} material={materials.e180_gray} />
          <mesh geometry={nodes.Object_196.geometry} material={materials.e180_black} />
          <mesh geometry={nodes.Object_197.geometry} material={materials.e180body} />
          <mesh geometry={nodes.Object_198.geometry} material={materials.e180_chrome} />
          <mesh geometry={nodes.Object_199.geometry} material={materials.e180_fog} />
          <mesh geometry={nodes.Object_201.geometry} material={materials.e180_glassred} />
          <mesh geometry={nodes.Object_203.geometry} material={materials.e180body} />
          <mesh geometry={nodes.Object_205.geometry} material={materials.e180_black} />
          <mesh geometry={nodes.Object_206.geometry} material={materials.e180_red} />
          <mesh geometry={nodes.Object_207.geometry} material={materials.e180body} />
          <mesh geometry={nodes.Object_208.geometry} material={materials.e180_chrome} />
          <mesh geometry={nodes.Object_209.geometry} material={materials.e180_gray} />
          <mesh geometry={nodes.Object_210.geometry} material={materials.e180_white} />
          <mesh geometry={nodes.Object_212.geometry} material={materials.e180_black} />
          <mesh geometry={nodes.Object_214.geometry} material={materials.e180_black} />
          <mesh geometry={nodes.Object_215.geometry} material={materials.e180_chrome} />
          <group position={[0.317, 0.781, 0.509]} rotation={[-1.226, 0, 0]}>
            <mesh geometry={nodes.Object_257.geometry} material={materials.e180_chrome} />
            <mesh geometry={nodes.Object_258.geometry} material={materials.e180_gray} />
            <mesh geometry={nodes.Object_259.geometry} material={materials.e180_interior} />
          </group>
          <mesh geometry={nodes.Object_217.geometry} material={materials.e180_black} />
          <mesh geometry={nodes.Object_218.geometry} material={materials.e180_red} />
          <mesh geometry={nodes.Object_219.geometry} material={materials.e180_chrome} />
          <mesh geometry={nodes.Object_220.geometry} material={materials.e180_gray} />
          <mesh geometry={nodes.Object_221.geometry} material={materials.e180_long} />
          <mesh geometry={nodes.Object_222.geometry} material={materials.e180_int} />
          <mesh geometry={nodes.Object_224.geometry} material={materials.e180_black} />
          <mesh geometry={nodes.Object_225.geometry} material={materials.e180_red} />
          <mesh geometry={nodes.Object_226.geometry} material={materials.e180_chrome} />
          <mesh geometry={nodes.Object_227.geometry} material={materials.e180_gray} />
          <mesh geometry={nodes.Object_228.geometry} material={materials.e180_short} />
          <mesh geometry={nodes.Object_229.geometry} material={materials.e180_int} />
          <mesh geometry={nodes.Object_230.geometry} material={materials.e180_tail} />
          <mesh geometry={nodes.Object_231.geometry} material={materials.e180_intlight} />
          <mesh geometry={nodes.Object_232.geometry} material={materials.e180_multi} />
          <mesh geometry={nodes.Object_234.geometry} material={materials.e180_black} />
          <mesh geometry={nodes.Object_235.geometry} material={materials.e180_glass} />
          <mesh geometry={nodes.Object_236.geometry} material={materials.e180_chrome} />
          <mesh geometry={nodes.Object_237.geometry} material={materials.e180_int} />
          <mesh geometry={nodes.Object_238.geometry} material={materials.e180_gauge} />
          <mesh geometry={nodes.Object_239.geometry} material={materials.e180_intlight} />
          <mesh geometry={nodes.Object_241.geometry} material={materials.e180_black} />
          <mesh geometry={nodes.Object_242.geometry} material={materials.e180_chrome} />
          <mesh geometry={nodes.Object_243.geometry} material={materials.e180_gray} />
          <mesh geometry={nodes.Object_244.geometry} material={materials.mirror} />
          <mesh geometry={nodes.Object_246.geometry} material={materials.e180_black} />
          <mesh geometry={nodes.Object_247.geometry} material={materials.e180_interior} />
          <mesh geometry={nodes.Object_249.geometry} material={materials.e180_black} />
          <mesh geometry={nodes.Object_250.geometry} material={materials.e180_chrome} />
          <mesh geometry={nodes.Object_252.geometry} material={materials.e180_black} />
          <mesh geometry={nodes.Object_253.geometry} material={materials.e180_chrome} />
          <mesh geometry={nodes.Object_254.geometry} material={materials.e180_gray} />
          <mesh geometry={nodes.Object_255.geometry} material={materials.e180_int} />
          <mesh geometry={nodes.Object_261.geometry} material={materials.e180_black} />
          <mesh geometry={nodes.Object_262.geometry} material={materials.e180body} />
          <mesh geometry={nodes.Object_263.geometry} material={materials.e180_gray} />
          <mesh geometry={nodes.Object_264.geometry} material={materials.e180_int} />
          <mesh geometry={nodes.Object_266.geometry} material={materials.e180_black} />
          <mesh geometry={nodes.Object_267.geometry} material={materials.e180_chrome} />
          <mesh geometry={nodes.Object_268.geometry} material={materials.e180_gray} />
          <mesh geometry={nodes.Object_274.geometry} material={materials.e180_black} position={[-0.767, 0.285, -1.28]} />
          <mesh geometry={nodes.Object_283.geometry} material={materials.e180_black} position={[0.767, 0.294, 1.31]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_292.geometry} material={materials.e180_black} position={[-0.767, 0.294, 1.31]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
