/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: BHP3D (https://sketchfab.com/BHP3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2022-toyota-hilux-82bd37c5065040098fb0b86e07fcb959
Title: 2022 Toyota Hilux
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../Revo/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.09}>
        <group position={[0, 100.98, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <group position={[0.788, 1.441, -0.628]}>
            <group position={[0, 0, -0.001]}>
              <mesh geometry={nodes.wheel_rf_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.wheel_rf_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.wheel_rf_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.wheel_rf_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.wheel_rf_wheel_rf4_0.geometry} material={materials['wheel_rf.4']} />
              <mesh geometry={nodes.wheel_rf_wheel_rf3_0.geometry} material={materials['wheel_rf.3']} />
              <mesh geometry={nodes.wheel_rf_wheel_rf6_0.geometry} material={materials['wheel_rf.6']} />
            </group>
            <group position={[0, -3.084, -0.001]}>
              <mesh geometry={nodes.wheel_rf001_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.wheel_rf001_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.wheel_rf001_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.wheel_rf001_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.wheel_rf001_wheel_rf4_0.geometry} material={materials['wheel_rf.4']} />
              <mesh geometry={nodes.wheel_rf001_wheel_rf3_0.geometry} material={materials['wheel_rf.3']} />
              <mesh geometry={nodes.wheel_rf001_wheel_rf6_0.geometry} material={materials['wheel_rf.6']} />
            </group>
            <group position={[-1.577, -3.084, -0.001]} scale={[-1, 1, 1]}>
              <mesh geometry={nodes.wheel_rf002_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.wheel_rf002_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.wheel_rf002_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.wheel_rf002_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.wheel_rf002_wheel_rf4_0.geometry} material={materials['wheel_rf.4']} />
              <mesh geometry={nodes.wheel_rf002_wheel_rf3_0.geometry} material={materials['wheel_rf.3']} />
              <mesh geometry={nodes.wheel_rf002_wheel_rf6_0.geometry} material={materials['wheel_rf.6']} />
            </group>
            <group position={[-1.577, 0, -0.001]} scale={[-1, 1, 1]}>
              <mesh geometry={nodes.wheel_rf003_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.wheel_rf003_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.wheel_rf003_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.wheel_rf003_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.wheel_rf003_wheel_rf4_0.geometry} material={materials['wheel_rf.4']} />
              <mesh geometry={nodes.wheel_rf003_wheel_rf3_0.geometry} material={materials['wheel_rf.3']} />
              <mesh geometry={nodes.wheel_rf003_wheel_rf6_0.geometry} material={materials['wheel_rf.6']} />
            </group>
          </group>
          <group position={[-0.005, -0.002, 0]}>
            <group position={[0.38, 0.5, 0.213]} rotation={[-0.355, 0, 0]}>
              <group position={[0, 0.023, 0.006]} rotation={[-0.071, 0, 0]}>
                <mesh geometry={nodes.movsteer_10_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
                <mesh geometry={nodes.movsteer_10_movsteer_107_0.geometry} material={materials['movsteer_1.0.7']} />
                <mesh geometry={nodes.movsteer_10_movsteer_108_0.geometry} material={materials['movsteer_1.0.8']} />
                <mesh geometry={nodes.movsteer_10_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
                <mesh geometry={nodes.movsteer_10_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
                <mesh geometry={nodes.movsteer_10_movsteer_102_0.geometry} material={materials['movsteer_1.0.2']} />
                <mesh geometry={nodes.movsteer_10_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
                <mesh geometry={nodes.movsteer_10_movsteer_104_0.geometry} material={materials['movsteer_1.0.4']} />
                <mesh geometry={nodes.movsteer_10_movsteer_106_0.geometry} material={materials['movsteer_1.0.6']} />
                <mesh geometry={nodes.movsteer_10_movsteer_109_0.geometry} material={materials['movsteer_1.0.9']} />
              </group>
            </group>
            <group position={[0.005, 2.442, -1.482]}>
              <mesh geometry={nodes.hilux_chassis_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.hilux_chassis_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.hilux_chassis_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.hilux_mb01_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.hilux_mb01_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.hilux_mb01_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.hilux_mb01_hilux_mb012_0.geometry} material={materials['hilux_mb01.2']} />
              <mesh geometry={nodes.hilux_mb01_movsteer_102_0.geometry} material={materials['movsteer_1.0.2']} />
              <mesh geometry={nodes.hilux_mb01_hilux_mb017_0.geometry} material={materials['hilux_mb01.7']} />
              <mesh geometry={nodes.hilux_mb01_hilux_mb016_0.geometry} material={materials['hilux_mb01.6']} />
              <mesh geometry={nodes.hilux_mb01_hilux_mb011_0.geometry} material={materials['hilux_mb01.1']} />
              <mesh geometry={nodes.hilux_mb02_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.hilux_mb02_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.hilux_mb02_hilux_mb020_0.geometry} material={materials['hilux_mb02.0']} />
              <mesh geometry={nodes.hilux_mb03_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.hilux_mb03_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.hilux_mb03_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.hilux_mb03_movsteer_102_0.geometry} material={materials['movsteer_1.0.2']} />
              <mesh geometry={nodes.hilux_mb03_hilux_mb031_0.geometry} material={materials['hilux_mb03.1']} />
              <mesh geometry={nodes.hilux_mb03_hilux_mb035_0.geometry} material={materials['hilux_mb03.5']} />
              <mesh geometry={nodes.hilux_mb04_hilux_mb012_0.geometry} material={materials['hilux_mb01.2']} />
              <mesh geometry={nodes.hilux_mb04_movsteer_102_0.geometry} material={materials['movsteer_1.0.2']} />
              <mesh geometry={nodes.hilux_mb05_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.hilux_mb05_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.hilux_mb05_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.hilux_mb05_hilux_mb054_0.geometry} material={materials['hilux_mb05.4']} />
              <mesh geometry={nodes.hilux_mb05_hilux_mb012_0.geometry} material={materials['hilux_mb01.2']} />
              <mesh geometry={nodes.hilux_mb05_movsteer_108_0.geometry} material={materials['movsteer_1.0.8']} />
              <mesh geometry={nodes.hilux_mb05_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.hilux_mb05_movsteer_102_0.geometry} material={materials['movsteer_1.0.2']} />
              <mesh geometry={nodes.hilux_mb05_movsteer_106_0.geometry} material={materials['movsteer_1.0.6']} />
              <mesh geometry={nodes.hilux_mb05_movsteer_109_0.geometry} material={materials['movsteer_1.0.9']} />
              <mesh geometry={nodes.hilux_mb05_hilux_mb017_0.geometry} material={materials['hilux_mb01.7']} />
              <mesh geometry={nodes.hilux_mb05_hilux_mb055_0.geometry} material={materials['hilux_mb05.5']} />
              <mesh geometry={nodes.hilux_mb05_hilux_mb051_0.geometry} material={materials['hilux_mb05.1']} />
              <mesh geometry={nodes.hilux_mb05_hilux_mb0513_0.geometry} material={materials['hilux_mb05.13']} />
              <mesh geometry={nodes.hilux_mb05_hilux_mb0511_0.geometry} material={materials['hilux_mb05.11']} />
              <mesh geometry={nodes.hilux_mb05_hilux_mb0512_0.geometry} material={materials['hilux_mb05.12']} />
              <mesh geometry={nodes.hilux_mb05_hilux_mb0514_0.geometry} material={materials['hilux_mb05.14']} />
              <mesh geometry={nodes.hilux_mb06_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.hilux_mb06_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.hilux_mb06_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.hilux_mb06_movsteer_102_0.geometry} material={materials['movsteer_1.0.2']} />
              <mesh geometry={nodes.hilux_mb06_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.hilux_mb06_hilux_mb0513_0.geometry} material={materials['hilux_mb05.13']} />
              <mesh geometry={nodes.hilux_mb07_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.hilux_mb07_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.hilux_mb07_hilux_mb054_0.geometry} material={materials['hilux_mb05.4']} />
              <mesh geometry={nodes.hilux_mb07_hilux_mb012_0.geometry} material={materials['hilux_mb01.2']} />
              <mesh geometry={nodes.hilux_mb07_movsteer_108_0.geometry} material={materials['movsteer_1.0.8']} />
              <mesh geometry={nodes.hilux_mb07_movsteer_102_0.geometry} material={materials['movsteer_1.0.2']} />
              <mesh geometry={nodes.hilux_mb07_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.hilux_mb07_movsteer_106_0.geometry} material={materials['movsteer_1.0.6']} />
              <mesh geometry={nodes.hilux_mb07_hilux_mb074_0.geometry} material={materials['hilux_mb07.4']} />
              <mesh geometry={nodes.hilux_mb07_hilux_mb0710_0.geometry} material={materials['hilux_mb07.10']} />
              <mesh geometry={nodes.hilux_mb07_hilux_mb077_0.geometry} material={materials['hilux_mb07.7']} />
              <mesh geometry={nodes.hilux_mb07_hilux_mb0711_0.geometry} material={materials['hilux_mb07.11']} />
              <mesh geometry={nodes.hilux_speedometer_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.hilux_speedometer_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.hilux_speedometer_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.hilux_speedometer_hilux_mb012_0.geometry} material={materials['hilux_mb01.2']} />
              <mesh geometry={nodes.hilux_speedometer_movsteer_108_0.geometry} material={materials['movsteer_1.0.8']} />
              <mesh geometry={nodes.hilux_speedometer_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.hilux_speedometer_movsteer_102_0.geometry} material={materials['movsteer_1.0.2']} />
              <mesh geometry={nodes.hilux_speedometer_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.hilux_speedometer_movsteer_106_0.geometry} material={materials['movsteer_1.0.6']} />
              <mesh geometry={nodes.hilux_speedometer_movsteer_109_0.geometry} material={materials['movsteer_1.0.9']} />
              <mesh geometry={nodes.hilux_speedometer_hilux_mb0513_0.geometry} material={materials['hilux_mb05.13']} />
              <mesh geometry={nodes.hilux_speedometer_hilux_mb077_0.geometry} material={materials['hilux_mb07.7']} />
              <mesh geometry={nodes.hilux_speedometer_hilux_speedometer11_0.geometry} material={materials['hilux_speedometer.11']} />
              <mesh geometry={nodes.hilux_speedometer_hilux_speedometer4_0.geometry} material={materials['hilux_speedometer.4']} />
              <mesh geometry={nodes.hilux_speedometer_hilux_speedometer5_0.geometry} material={materials['hilux_speedometer.5']} />
              <mesh geometry={nodes.speedometer_glass_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.hilux_dashboard_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.hilux_dashboard_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.hilux_dashboard_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.hilux_dashboard_hilux_mb012_0.geometry} material={materials['hilux_mb01.2']} />
              <mesh geometry={nodes.hilux_dashboard_movsteer_107_0.geometry} material={materials['movsteer_1.0.7']} />
              <mesh geometry={nodes.hilux_dashboard_movsteer_108_0.geometry} material={materials['movsteer_1.0.8']} />
              <mesh geometry={nodes.hilux_dashboard_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.hilux_dashboard_movsteer_102_0.geometry} material={materials['movsteer_1.0.2']} />
              <mesh geometry={nodes.hilux_dashboard_movsteer_106_0.geometry} material={materials['movsteer_1.0.6']} />
              <mesh geometry={nodes.hilux_dashboard_movsteer_109_0.geometry} material={materials['movsteer_1.0.9']} />
              <mesh geometry={nodes.hilux_dashboard_hilux_mb0513_0.geometry} material={materials['hilux_mb05.13']} />
              <mesh geometry={nodes.hilux_dashboard_hilux_mb0511_0.geometry} material={materials['hilux_mb05.11']} />
              <mesh geometry={nodes.hilux_dashboard_hilux_mb077_0.geometry} material={materials['hilux_mb07.7']} />
              <mesh geometry={nodes.hilux_dashboard_hilux_speedometer4_0.geometry} material={materials['hilux_speedometer.4']} />
              <mesh geometry={nodes.hilux_dashboard_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.hilux_dashboard_hilux_dashboard3_0.geometry} material={materials['hilux_dashboard.3']} />
              <mesh geometry={nodes.screen_glass_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.hilux_headlight_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.hilux_headlight_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.hilux_headlight_hilux_mb012_0.geometry} material={materials['hilux_mb01.2']} />
              <mesh geometry={nodes.hilux_headlight_hilux_mb016_0.geometry} material={materials['hilux_mb01.6']} />
              <mesh geometry={nodes.hilux_headlight_hilux_headlight0_0.geometry} material={materials['hilux_headlight.0']} />
              <mesh geometry={nodes.indicators_lf_indicator_lf_0.geometry} material={materials.indicator_lf} position={[-0.795, -0.583, 1.529]} />
              <mesh geometry={nodes.indicators_rf_indicator_rf_0.geometry} material={materials.indicator_rf} position={[0.795, -0.583, 1.529]} />
              <mesh geometry={nodes.headlight_led_right_front_light_0.geometry} material={materials.right_front_light} />
              <mesh geometry={nodes.foglight_l_foglight_l_0.geometry} material={materials.foglight_l} position={[-0.767, -0.361, 1.095]} />
              <mesh geometry={nodes.foglight_r_foglight_r_0.geometry} material={materials.foglight_r} position={[0.771, -0.361, 1.092]} />
              <mesh geometry={nodes.headlight_glass_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.headlight_glass_glass001_0.geometry} material={materials['glass.001']} />
              <mesh geometry={nodes.foglight_glass_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.hilux_seat_mech_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.hilux_seat_mech_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.hilux_seat_mech_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.hilux_seat_mech_hilux_mb054_0.geometry} material={materials['hilux_mb05.4']} />
              <mesh geometry={nodes.hilux_seat_mech_hilux_mb012_0.geometry} material={materials['hilux_mb01.2']} />
              <mesh geometry={nodes.hilux_seat_mech_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.hilux_seat_mech_movsteer_102_0.geometry} material={materials['movsteer_1.0.2']} />
              <mesh geometry={nodes.hilux_seat_mech_movsteer_106_0.geometry} material={materials['movsteer_1.0.6']} />
              <mesh geometry={nodes.hilux_seat_mech_hilux_mb017_0.geometry} material={materials['hilux_mb01.7']} />
              <mesh geometry={nodes.hilux_seat_mech_hilux_mb051_0.geometry} material={materials['hilux_mb05.1']} />
              <mesh geometry={nodes.hilux_seat_mech_hilux_mb0513_0.geometry} material={materials['hilux_mb05.13']} />
              <mesh geometry={nodes.hilux_seat_mech_hilux_seat_mech11_0.geometry} material={materials['hilux_seat_mech.11']} />
              <mesh geometry={nodes.seats_movsteer_107_0.geometry} material={materials['movsteer_1.0.7']} />
              <mesh geometry={nodes.seats_movsteer_108_0.geometry} material={materials['movsteer_1.0.8']} />
              <mesh geometry={nodes.seats_hilux_mb0511_0.geometry} material={materials['hilux_mb05.11']} />
              <mesh geometry={nodes.hilux_taillight_l_left_rear_light_0.geometry} material={materials.left_rear_light} />
              <mesh geometry={nodes.rev_light_l_revlight_L_0.geometry} material={materials.revlight_L} position={[-0.753, -5.223, 1.581]} />
              <mesh geometry={nodes.rev_light_r_revlight_r_0.geometry} material={materials.revlight_r} position={[0.753, -5.223, 1.581]} />
              <mesh geometry={nodes.indicator_lr001_indicator_lr_0.geometry} material={materials.indicator_lr} position={[-0.758, -5.2, 1.401]} />
              <mesh geometry={nodes.indicator_rr001_indicator_rr_0.geometry} material={materials.indicator_rr} position={[0.758, -5.2, 1.401]} />
              <mesh geometry={nodes.hilux_taillight_r_right_rear_light_0.geometry} material={materials.right_rear_light} />
              <mesh geometry={nodes.taillight_glass_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.taillight_glass_glass002_0.geometry} material={materials['glass.002']} />
              <mesh geometry={nodes.windscreen_glass001_0.geometry} material={materials['glass.001']} />
              <mesh geometry={nodes.windscreen_r_glass001_0.geometry} material={materials['glass.001']} />
            </group>
            <group position={[-0.843, 0.948, 0.092]}>
              <mesh geometry={nodes.door_lf_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.door_lf_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.door_lf_movsteer_107_0.geometry} material={materials['movsteer_1.0.7']} />
              <mesh geometry={nodes.door_lf_movsteer_108_0.geometry} material={materials['movsteer_1.0.8']} />
              <mesh geometry={nodes.door_lf_movsteer_106_0.geometry} material={materials['movsteer_1.0.6']} />
              <mesh geometry={nodes.door_lf_movsteer_109_0.geometry} material={materials['movsteer_1.0.9']} />
              <mesh geometry={nodes.door_lf_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.door_lf_hilux_mb017_0.geometry} material={materials['hilux_mb01.7']} />
              <mesh geometry={nodes.door_lf_hilux_mb0513_0.geometry} material={materials['hilux_mb05.13']} />
              <mesh geometry={nodes.door_lf_hilux_mb0511_0.geometry} material={materials['hilux_mb05.11']} />
              <mesh geometry={nodes.door_lf_hilux_mb077_0.geometry} material={materials['hilux_mb07.7']} />
              <mesh geometry={nodes.door_lf_hilux_mb0711_0.geometry} material={materials['hilux_mb07.11']} />
              <mesh geometry={nodes.door_lf_movsteer_102_0.geometry} material={materials['movsteer_1.0.2']} />
              <mesh geometry={nodes.door_lf_door_lf12_0.geometry} material={materials['door_lf.12']} />
              <mesh geometry={nodes.door_lf_hilux_mb031_0.geometry} material={materials['hilux_mb03.1']} />
              <mesh geometry={nodes.door_lf_hilux_mb012_0.geometry} material={materials['hilux_mb01.2']} />
              <mesh geometry={nodes.door_lf_door_lf14_0.geometry} material={materials['door_lf.14']} />
              <mesh geometry={nodes.indicator_lm_indicator_lm_0.geometry} material={materials.indicator_lm} />
              <mesh geometry={nodes.door_lf_glass_glass001_0.geometry} material={materials['glass.001']} />
              <mesh geometry={nodes.door_lf_indicator_g_glass_0.geometry} material={materials.glass} />
            </group>
            <group position={[0.853, 0.948, 0.092]}>
              <mesh geometry={nodes.door_rf_wheel_rf1_0.geometry} material-color={'0xfffff'} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.door_rf_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.door_rf_movsteer_107_0.geometry} material={materials['movsteer_1.0.7']} />
              <mesh geometry={nodes.door_rf_movsteer_108_0.geometry} material={materials['movsteer_1.0.8']} />
              <mesh geometry={nodes.door_rf_movsteer_106_0.geometry} material={materials['movsteer_1.0.6']} />
              <mesh geometry={nodes.door_rf_movsteer_109_0.geometry} material={materials['movsteer_1.0.9']} />
              <mesh geometry={nodes.door_rf_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.door_rf_hilux_mb017_0.geometry} material={materials['hilux_mb01.7']} />
              <mesh geometry={nodes.door_rf_hilux_mb0513_0.geometry} material={materials['hilux_mb05.13']} />
              <mesh geometry={nodes.door_rf_hilux_mb0511_0.geometry} material={materials['hilux_mb05.11']} />
              <mesh geometry={nodes.door_rf_hilux_mb077_0.geometry} material={materials['hilux_mb07.7']} />
              <mesh geometry={nodes.door_rf_hilux_mb0711_0.geometry} material={materials['hilux_mb07.11']} />
              <mesh geometry={nodes.door_rf_movsteer_102_0.geometry} material={materials['movsteer_1.0.2']} />
              <mesh geometry={nodes.door_rf_door_lf12_0.geometry} material={materials['door_lf.12']} />
              <mesh geometry={nodes.door_rf_hilux_mb031_0.geometry} material={materials['hilux_mb03.1']} />
              <mesh geometry={nodes.door_rf_hilux_mb012_0.geometry} material={materials['hilux_mb01.2']} />
              <mesh geometry={nodes.door_rf_door_rf14_0.geometry} material={materials['door_rf.14']} />
              <mesh geometry={nodes.door_rf_indicator_g_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.indicator_rm_indicator_rm_0.geometry} material={materials.indicator_rm} />
              <mesh geometry={nodes.door_rf_glass_glass001_0.geometry} material={materials['glass.001']} />
            </group>
            <group position={[0.871, -0.117, 0.097]}>
              <mesh geometry={nodes.door_rr_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.door_rr_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.door_rr_movsteer_107_0.geometry} material={materials['movsteer_1.0.7']} />
              <mesh geometry={nodes.door_rr_movsteer_108_0.geometry} material={materials['movsteer_1.0.8']} />
              <mesh geometry={nodes.door_rr_movsteer_106_0.geometry} material={materials['movsteer_1.0.6']} />
              <mesh geometry={nodes.door_rr_movsteer_109_0.geometry} material={materials['movsteer_1.0.9']} />
              <mesh geometry={nodes.door_rr_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.door_rr_hilux_mb0513_0.geometry} material={materials['hilux_mb05.13']} />
              <mesh geometry={nodes.door_rr_hilux_mb0511_0.geometry} material={materials['hilux_mb05.11']} />
              <mesh geometry={nodes.door_rr_hilux_mb077_0.geometry} material={materials['hilux_mb07.7']} />
              <mesh geometry={nodes.door_rr_movsteer_102_0.geometry} material={materials['movsteer_1.0.2']} />
              <mesh geometry={nodes.door_rr_hilux_mb012_0.geometry} material={materials['hilux_mb01.2']} />
              <mesh geometry={nodes.door_rr_door_lf14_0.geometry} material={materials['door_lf.14']} />
              <mesh geometry={nodes.door_rr_door_rf14_0.geometry} material={materials['door_rf.14']} />
              <mesh geometry={nodes.door_rr_glass_glass001_0.geometry} material={materials['glass.001']} />
            </group>
            <group position={[-0.86, -0.117, 0.097]}>
              <mesh geometry={nodes.door_lr_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.door_lr_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.door_lr_movsteer_107_0.geometry} material={materials['movsteer_1.0.7']} />
              <mesh geometry={nodes.door_lr_movsteer_108_0.geometry} material={materials['movsteer_1.0.8']} />
              <mesh geometry={nodes.door_lr_movsteer_106_0.geometry} material={materials['movsteer_1.0.6']} />
              <mesh geometry={nodes.door_lr_movsteer_109_0.geometry} material={materials['movsteer_1.0.9']} />
              <mesh geometry={nodes.door_lr_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.door_lr_hilux_mb017_0.geometry} material={materials['hilux_mb01.7']} />
              <mesh geometry={nodes.door_lr_hilux_mb0513_0.geometry} material={materials['hilux_mb05.13']} />
              <mesh geometry={nodes.door_lr_hilux_mb0511_0.geometry} material={materials['hilux_mb05.11']} />
              <mesh geometry={nodes.door_lr_hilux_mb077_0.geometry} material={materials['hilux_mb07.7']} />
              <mesh geometry={nodes.door_lr_movsteer_102_0.geometry} material={materials['movsteer_1.0.2']} />
              <mesh geometry={nodes.door_lr_hilux_mb012_0.geometry} material={materials['hilux_mb01.2']} />
              <mesh geometry={nodes.door_lr_door_lf14_0.geometry} material={materials['door_lf.14']} />
              <mesh geometry={nodes.door_lr_door_rf14_0.geometry} material={materials['door_rf.14']} />
              <mesh geometry={nodes.door_lr_glass_glass001_0.geometry} material={materials['glass.001']} />
            </group>
            <group position={[0.005, -2.793, -0.282]}>
              <mesh geometry={nodes.boot_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.boot_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.boot_hilux_mb016_0.geometry} material={materials['hilux_mb01.6']} />
              <mesh geometry={nodes.boot_movsteer_102_0.geometry} material={materials['movsteer_1.0.2']} />
              <mesh geometry={nodes.boot_hilux_mb012_0.geometry} material={materials['hilux_mb01.2']} />
              <mesh geometry={nodes.boot_boot5_0.geometry} material={materials['boot.5']} />
              <mesh geometry={nodes.boot_hilux_mb020_0.geometry} material={materials['hilux_mb02.0']} />
              <mesh geometry={nodes.boot_taillight_right_rear_light_0.geometry} material={materials.right_rear_light} />
              <mesh geometry={nodes.boot_light_glass_glass002_0.geometry} material={materials['glass.002']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
