/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: 3DDomino (https://sketchfab.com/3DDomino)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rim-1e910698e1974d81869d3fb873360af3
Title: Rim
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../Rims/Rim1/scene.gltf')

  return (
    <group {...props} dispose={null}>
      <group scale={props.size} position={props.position} rotation={props.rot} >
        <mesh geometry={nodes.felna_Steel_Rough_0.geometry} material-color={props.updatecolor} material={materials.Steel_Rough} />
        <mesh geometry={nodes.felna_Steel_Polished_0.geometry} material-color={props.updatecolor} material={materials.Steel_Polished} />
        <mesh geometry={nodes.felna_Tire_0.geometry} material-color={props.updatecolor} material={materials.Tire} />
        <mesh geometry={nodes.felna_Tire_0_1.geometry} material={materials.Tire_0} />
        <mesh geometry={nodes.felna_Tire_0_2.geometry} material={materials.Tire_1} />
        <mesh geometry={nodes.felna_Tire_0_3.geometry} material={materials.Tire_2} />
        <mesh geometry={nodes.felna_Steel_Rough_0_1.geometry} material={materials.Steel_Rough_0} />
        <mesh geometry={nodes.felna_Steel_Rough_0_2.geometry} material={materials.Steel_Rough_1} />
        <mesh geometry={nodes.felna_Steel_Rough_0_3.geometry} material={materials.Steel_Rough_2} />
        <mesh geometry={nodes.felna_Steel_Rough_0_4.geometry} material={materials.Steel_Rough_3} />
        <mesh geometry={nodes.felna_Steel_Rough_0_5.geometry} material={materials.Steel_Rough_4} />
        <mesh geometry={nodes.felna_Steel_Rough_0_6.geometry} material={materials.Steel_Rough_5} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
