/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Nordic_Face (https://sketchfab.com/Nordic_Face)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rim-7c71688ce0be4767ac561cccc6ccdebe
Title: RIM
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../Rims/Rim2/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={props.size} rotation={props.rot}>
        <group position={props.position} scale={[671.614, 671.614, 18.875]}>
          <mesh geometry={nodes.Cylinder001_Material_0.geometry} material-color={props.updatecolor} material={materials.Material} />
          <mesh geometry={nodes.Cylinder001_Material001_0.geometry} material-color={props.updatecolor} material={materials['Material.001']} />
        </group>
        <mesh geometry={nodes.Cube003_Material002_0.geometry} material={materials['Material.002']} position={[-0.018, 0.464, -0.743]} rotation={[-Math.PI / 2, 0, 0]} scale={[53.23, 100, 7.418]} />
        <mesh geometry={nodes.Cylinder_Material002_0.geometry} material={materials['Material.002']} position={[0, 0, -0.005]} scale={[757.643, 757.643, 205.772]} />
        <mesh geometry={nodes.Plane006_Material_0.geometry} material={materials.Material} position={[5.814, 2.335, -160.383]} rotation={[0, 0, -1.528]} scale={22.965} />
        <mesh geometry={nodes.Cylinder002_Material_0.geometry} material={materials.Material} position={[0, 0, -202.961]} scale={100} />
        <mesh geometry={nodes.Cylinder003_Material003_0.geometry} material={materials['Material.003']} position={[504.27, 213.029, -149.336]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[10.859, 10.859, 2.219]} />
        <mesh geometry={nodes.Cylinder005_Material003_0.geometry} material={materials['Material.003']} position={[400.377, 376.942, -149.336]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[10.859, 10.859, 2.219]} />
        <mesh geometry={nodes.Cylinder006_Material003_0.geometry} material={materials['Material.003']} position={[215.008, 501.259, -149.336]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[10.859, 10.859, 2.219]} />
        <mesh geometry={nodes.Cylinder007_Material003_0.geometry} material={materials['Material.003']} position={[20.79, 545.942, -149.336]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[10.859, 10.859, 2.219]} />
        <mesh geometry={nodes.Cylinder008_Material003_0.geometry} material={materials['Material.003']} position={[-202.184, 510.549, -149.336]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[10.859, 10.859, 2.219]} />
        <mesh geometry={nodes.Cylinder009_Material003_0.geometry} material={materials['Material.003']} position={[-368.531, 395.523, -149.336]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[10.859, 10.859, 2.219]} />
        <mesh geometry={nodes.Cylinder010_Material003_0.geometry} material={materials['Material.003']} position={[-498.599, 200.42, -149.336]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[10.859, 10.859, 2.219]} />
        <mesh geometry={nodes.Cylinder011_Material003_0.geometry} material={materials['Material.003']} position={[-541.07, 15.05, -149.336]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[10.859, 10.859, 2.219]} />
        <mesh geometry={nodes.Cylinder012_Material003_0.geometry} material={materials['Material.003']} position={[-491.963, -202.615, -149.336]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[10.859, 10.859, 2.219]} />
        <mesh geometry={nodes.Cylinder013_Material003_0.geometry} material={materials['Material.003']} position={[-388.439, -372.5, -149.336]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[10.859, 10.859, 2.219]} />
        <mesh geometry={nodes.Cylinder014_Material003_0.geometry} material={materials['Material.003']} position={[-199.972, -503.896, -149.336]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[10.859, 10.859, 2.219]} />
        <mesh geometry={nodes.Cylinder015_Material003_0.geometry} material={materials['Material.003']} position={[-2.658, -539.731, -149.336]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[10.859, 10.859, 2.219]} />
        <mesh geometry={nodes.Cylinder016_Material003_0.geometry} material={materials['Material.003']} position={[216.777, -505.666, -149.336]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[10.859, 10.859, 2.219]} />
        <mesh geometry={nodes.Cylinder017_Material003_0.geometry} material={materials['Material.003']} position={[378.699, -389.754, -149.336]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[10.859, 10.859, 2.219]} />
        <mesh geometry={nodes.Cylinder018_Material003_0.geometry} material={materials['Material.003']} position={[506.113, -196.421, -149.336]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[10.859, 10.859, 2.219]} />
        <mesh geometry={nodes.Cylinder019_Material003_0.geometry} material={materials['Material.003']} position={[549.912, -6.628, -149.336]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[10.859, 10.859, 2.219]} />
        <mesh geometry={nodes.Cylinder020_Material003_0.geometry} material={materials['Material.003']} position={[118.364, 98.073, -136.856]} scale={[24.528, 24.528, 47.15]} />
        <mesh geometry={nodes.Cylinder004_Material003_0.geometry} material={materials['Material.003']} position={[137.83, -75.352, -137.014]} scale={[24.528, 24.528, 47.15]} />
        <mesh geometry={nodes.Cylinder021_Material003_0.geometry} material={materials['Material.003']} position={[-25.419, -150.563, -136.615]} scale={[24.769, 24.769, 47.613]} />
        <mesh geometry={nodes.Cylinder022_Material003_0.geometry} material={materials['Material.003']} position={[-148.409, -11.204, -136.615]} scale={[24.769, 24.769, 47.613]} />
        <mesh geometry={nodes.Cylinder023_Material003_0.geometry} material={materials['Material.003']} position={[-51.964, 145.852, -136.875]} scale={[24.769, 24.769, 47.613]} />
        <mesh geometry={nodes.Cylinder024_Material_0.geometry} material={materials.Material} position={[2.95, 7.061, 28.787]} rotation={[0, 0, Math.PI / 2]} scale={146.266} />
        <mesh geometry={nodes.Cylinder025_Material005_0.geometry} material={materials['Material.005']} position={[5.025, 6.324, -72.96]} scale={[341.961, 341.961, 10.598]} />
        <mesh geometry={nodes.Cylinder026_Material005_0.geometry} material={materials['Material.005']} position={[5.025, 6.324, -44.727]} scale={[341.961, 341.961, 10.598]} />
        <mesh geometry={nodes.Cylinder027_Material003_0.geometry} material={materials['Material.003']} position={[202.567, 5.69, -99.101]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[15.076, 15.076, 3.08]} />
        <mesh geometry={nodes.Cylinder028_Material003_0.geometry} material={materials['Material.003']} position={[175.02, -94.227, -99.101]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[15.076, 15.076, 3.08]} />
        <mesh geometry={nodes.Cylinder029_Material003_0.geometry} material={materials['Material.003']} position={[103.088, -166.051, -99.101]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[15.076, 15.076, 3.08]} />
        <mesh geometry={nodes.Cylinder030_Material003_0.geometry} material={materials['Material.003']} position={[3.373, -193.942, -99.101]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[15.076, 15.076, 3.08]} />
        <mesh geometry={nodes.Cylinder031_Material003_0.geometry} material={materials['Material.003']} position={[-99.067, -165.589, -99.101]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[15.076, 15.076, 3.08]} />
        <mesh geometry={nodes.Cylinder032_Material003_0.geometry} material={materials['Material.003']} position={[-169.446, -92.284, -99.101]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[15.076, 15.076, 3.08]} />
        <mesh geometry={nodes.Cylinder033_Material003_0.geometry} material={materials['Material.003']} position={[-197.48, 7.823, -99.101]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[15.076, 15.076, 3.08]} />
        <mesh geometry={nodes.Cylinder034_Material003_0.geometry} material={materials['Material.003']} position={[-170.299, 105.536, -99.101]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[15.076, 15.076, 3.08]} />
        <mesh geometry={nodes.Cylinder035_Material003_0.geometry} material={materials['Material.003']} position={[-93.06, 182.182, -99.101]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[15.076, 15.076, 3.08]} />
        <mesh geometry={nodes.Cylinder036_Material003_0.geometry} material={materials['Material.003']} position={[2.946, 207.348, -99.101]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[15.076, 15.076, 3.08]} />
        <mesh geometry={nodes.Cylinder037_Material003_0.geometry} material={materials['Material.003']} position={[106.596, 177.36, -99.101]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[15.076, 15.076, 3.08]} />
        <mesh geometry={nodes.Cylinder038_Material003_0.geometry} material={materials['Material.003']} position={[177.828, 102.514, -99.101]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[15.076, 15.076, 3.08]} />
        <mesh geometry={nodes.Cube001_Material001_0.geometry} material={materials['Material.001']} position={[221.557, 225.177, -59.554]} rotation={[Math.PI / 2, 0.776, Math.PI]} scale={[138.834, 28.091, 138.834]} />
        <mesh geometry={nodes.Cylinder039_Material004_0.geometry} material={materials['Material.004']} position={[145.655, 365.824, -63.877]} rotation={[0, 0, -2.366]} scale={[5.451, 5.451, 81.621]} />
        <mesh geometry={nodes.Cylinder043_Material004_0.geometry} material={materials['Material.004']} position={[254.065, 255.347, -59.077]} rotation={[0, 0, -2.366]} scale={[19.267, 19.267, 31.696]} />
        <mesh geometry={nodes.Cylinder040_Material003_0.geometry} material={materials['Material.003']} position={[145.69, 365.792, -96.536]} rotation={[-Math.PI, 0, -2.347]} scale={[4.29, 4.29, 0.877]} />
        <mesh geometry={nodes.Cylinder041_Material003_0.geometry} material={materials['Material.003']} position={[137.213, 374.431, -96.536]} rotation={[-Math.PI, 0, -2.347]} scale={[4.29, 4.29, 0.877]} />
        <mesh geometry={nodes.Cylinder042_Material003_0.geometry} material={materials['Material.003']} position={[372.349, 134.812, -96.536]} rotation={[-Math.PI, 0, -2.347]} scale={[4.29, 4.29, 0.877]} />
        <mesh geometry={nodes.Cylinder044_Material003_0.geometry} material={materials['Material.003']} position={[363.871, 143.451, -96.536]} rotation={[-Math.PI, 0, -2.347]} scale={[4.29, 4.29, 0.877]} />
        <mesh geometry={nodes.Cylinder045_Material003_0.geometry} material={materials['Material.003']} position={[145.69, 365.792, -27.271]} rotation={[0, 0, 2.347]} scale={[4.29, 4.29, 0.877]} />
        <mesh geometry={nodes.Cylinder046_Material003_0.geometry} material={materials['Material.003']} position={[137.213, 374.431, -27.271]} rotation={[0, 0, 2.347]} scale={[4.29, 4.29, 0.877]} />
        <mesh geometry={nodes.Cylinder047_Material003_0.geometry} material={materials['Material.003']} position={[372.349, 134.812, -27.271]} rotation={[0, 0, 2.347]} scale={[4.29, 4.29, 0.877]} />
        <mesh geometry={nodes.Cylinder048_Material003_0.geometry} material={materials['Material.003']} position={[363.871, 143.451, -27.271]} rotation={[0, 0, 2.347]} scale={[4.29, 4.29, 0.877]} />
        <mesh geometry={nodes.Cylinder049_Material003_0.geometry} material={materials['Material.003']} position={[254.197, 255.216, -92.308]} rotation={[-Math.PI, 0, -2.347]} scale={[9.909, 9.909, 2.025]} />
        <mesh geometry={nodes.Cylinder050_Material003_0.geometry} material={materials['Material.003']} position={[254.197, 255.216, -27.466]} rotation={[0, 0, 2.347]} scale={[9.909, 9.909, 2.025]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
