/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 scene.gltf 
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-wheels-rst-carbon-sdc-72d881058d4b490c8b408c655e962801
Title: (FREE) Wheels - RST-Carbon SDC
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../Rims/Rim3/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={props.position} rotation={props.rot} scale={props.size}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['plaquette_de_frein.002']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['visse.002']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['CRBN_JANTE.002']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['pneu.005']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.059']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.060']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.061']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['PZEO.001']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.CRBN_JANTE} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['jente.001']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['plaquette_de_frein.005']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
