/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: the_86_guy (https://sketchfab.com/the_86_guy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/universal-spoiler-2-d5ba2afc8faa496d95b64cb985b94a69
Title: Universal Spoiler 2
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../Spoilers/Spoiler1/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 1.85]} scale={0.08}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={props.position} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 16.373, 100]}>
            <mesh geometry={nodes.Plane_Carbon_0.geometry} material={materials.Carbon} />
            <mesh geometry={nodes.Plane_Feet_0.geometry} material={materials.Feet} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
