/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Asadawut.Kaewma (https://sketchfab.com/Asadawut.Kaewma)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toyota-fortuner-2021-a70b997f11b7482e9affbf318a508f85
Title: Toyota Fortuner 2021
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../Fortuner/scene.gltf')
  return (
    <group {...props} dispose={null} scale={5}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 1.034, 1.597]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes['Object054_Material_#4_0'].geometry} material={materials.Material_4} position={[1.174, 0.652, -4.856]} />
            <mesh geometry={nodes.Object055_chrome_0.geometry} material={materials.chrome} position={[-0.005, -10.334, -2.406]} />
            <mesh geometry={nodes['Object056_Material_#164_0'].geometry} material={materials.Material_164} position={[0, -3.419, -1.067]} />
            <mesh geometry={nodes.Object097_black_0.geometry} material={materials.black} position={[-1.571, 1.194, -4.853]} />
            <mesh geometry={nodes.Object268_black_0.geometry} material={materials.black} position={[0.078, -0.352, -0.851]} />
            <mesh geometry={nodes['Object001_Material_#8_0'].geometry} material={materials.Material_8} />
          </group>
          <group position={[0.02, 0.812, 0.148]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Object186_stitch_0.geometry} material={materials.stitch} position={[-2.055, 14.162, 1.011]} />
            <mesh geometry={nodes.TOYOTA_FORTUNER_IN_DMTBB_DMTAB_PMTAB_PANEL_CONSOLE_MESH_decal_int_0.geometry} material={materials.decal_int} position={[-1.952, -0.155, 7.373]} />
            <mesh geometry={nodes.Object178_black_int_0.geometry} material={materials.black_int} position={[-1.952, -0.155, 7.373]} />
            <mesh geometry={nodes.Object179_black_metallic_int_0.geometry} material={materials.black_metallic_int} position={[-1.952, -0.155, 7.373]} />
            <mesh geometry={nodes.Object180_black_second_int_0.geometry} material={materials.black_second_int} position={[-1.952, -0.155, 7.373]} />
            <mesh geometry={nodes.Object181_black_second_int_0.geometry} material={materials.black_second_int} position={[-1.952, -0.155, 7.373]} />
            <mesh geometry={nodes.Object182_leather_0.geometry} material={materials.leather} position={[-1.952, -0.155, 7.373]} />
            <mesh geometry={nodes.Object183_black_second_int_0.geometry} material={materials.black_second_int} position={[-1.952, -0.155, 7.373]} />
            <mesh geometry={nodes.Object184_chrome_int_0.geometry} material={materials.chrome_int} position={[-1.952, -0.155, 7.373]} />
            <mesh geometry={nodes.Object185_stitch_0.geometry} material={materials.stitch} position={[-1.952, -0.155, 7.373]} />
            <mesh geometry={nodes.Object188_leather_0.geometry} material={materials.leather} position={[-1.942, 42.489, 13.985]} />
            <mesh geometry={nodes.TOYOTA_FORTUNER_IN_DMTBb_DATBb_DATAb_ARM_REST_MESH_stitch_0.geometry} material={materials.stitch} position={[-1.942, 42.489, 13.985]} />
            <mesh geometry={nodes.Object191_black_second_int_0.geometry} material={materials.black_second_int} position={[-2.055, 14.162, 1.011]} />
            <mesh geometry={nodes.Object192_black_second_int_0.geometry} material={materials.black_second_int} position={[-2.055, 14.162, 1.011]} />
            <mesh geometry={nodes.Object193_chrome_only_0.geometry} material={materials.chrome_only} position={[-2.055, 14.162, 1.011]} />
            <mesh geometry={nodes.Object194_leather_0.geometry} material={materials.leather} position={[-2.055, 14.162, 1.011]} />
            <mesh geometry={nodes.Object189_black_second_int_0.geometry} material={materials.black_second_int} position={[-2.055, 14.162, 1.011]} />
            <mesh geometry={nodes.Object190_black_second_int_0.geometry} material={materials.black_second_int} position={[-2.055, 14.162, 1.011]} />
            <mesh geometry={nodes.Object187_black_second_int_0.geometry} material={materials.black_second_int} position={[-2.055, 14.162, 1.011]} />
            <mesh geometry={nodes.TOYOTA_FORTUNER_IN_CENTER_CONSOLE_MESH_chrome_only_0.geometry} material={materials.chrome_only} position={[-2.055, 14.162, 1.011]} />
            <mesh geometry={nodes.Object195_black_second_int_0.geometry} material={materials.black_second_int} position={[-2.055, 14.162, 1.011]} />
          </group>
          <group position={[-0.367, 1.199, 0.463]} rotation={[-Math.PI / 2, 0, 0]} scale={0.002}>
            <mesh geometry={nodes.Object131_decal_int_0.geometry} material={materials.decal_int} position={[-0.065, 39.259, -17.838]} scale={3.922} />
            <mesh geometry={nodes['Object130_Material_#20_0'].geometry} material={materials.Material_20} position={[-0.065, 39.259, -17.838]} scale={3.922} />
            <mesh geometry={nodes['Object122_Material_#20_0'].geometry} material={materials.Material_20} position={[-0.065, 39.259, -17.838]} scale={3.922} />
            <mesh geometry={nodes['Object018_Material_#8_0'].geometry} material={materials.Material_8} scale={3.922} />
            <mesh geometry={nodes['Object128_Material_#20_0'].geometry} material={materials.Material_20} position={[-0.065, 39.259, -17.838]} scale={3.922} />
            <mesh geometry={nodes.TOYOTA_FORTUNER_IN_STEERING_SPEEDO_MESH_decal_int_0.geometry} material={materials.decal_int} position={[-0.065, 39.259, -17.838]} scale={3.922} />
          </group>
          <group position={[0.001, 1.065, 0.541]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.TOYOTA_FORTUNER_IN_DASHBOARD_MESH_black_metallic_int_0.geometry} material={materials.black_metallic_int} position={[0, 2.227, 0.615]} />
            <mesh geometry={nodes.TOYOTA_FORTUNER_IN_DMTAB_DATAB_PMTAB_PATAB_KNOBS_AND_BUTTONS_ME_decal_int_0.geometry} material={materials.decal_int} position={[1.987, 13.86, -14.69]} />
            <mesh geometry={nodes.TOYOTA_FORTUNER_IN_DMTBb_DATBb_DATAb_BROWN_DASH_GUARD_MESH_stitch_0.geometry} material={materials.stitch} position={[0.503, 12.632, -3.703]} />
            <mesh geometry={nodes.TOYOTA_FORTUNER_IN_DMTBB_DMTAB_PMTAB_PEDALS_MESH_plastic_1_0.geometry} material={materials.plastic_1} position={[-41.426, -4.544, -17.706]} />
            <mesh geometry={nodes.TOYOTA_IN_DASH_LOGO_MESH_decal_int_0.geometry} material={materials.decal_int} position={[2.207, 23.467, 5.153]} />
            <mesh geometry={nodes.Object123_plastic_1_0.geometry} material={materials.plastic_1} position={[-37.568, 17.953, 9.146]} />
            <mesh geometry={nodes.Object124_stitch_0.geometry} material={materials.stitch} position={[-37.568, 17.953, 9.146]} />
            <mesh geometry={nodes.Object125_decal_int_0.geometry} material={materials.decal_int} position={[-37.568, 17.953, 9.146]} />
            <mesh geometry={nodes.Object167_black_metallic_int_0.geometry} material={materials.black_metallic_int} position={[-41.426, -4.544, -17.706]} />
            <mesh geometry={nodes.Object143_black_metallic_int_0.geometry} material={materials.black_metallic_int} position={[0, 2.227, 0.615]} />
            <mesh geometry={nodes.Object166_plastic_1_0.geometry} material={materials.plastic_1} position={[1.987, 13.86, -14.69]} />
            <mesh geometry={nodes.Object145_acnt_int_0.geometry} material={materials.acnt_int} position={[0.503, 12.632, -3.703]} />
            <mesh geometry={nodes.Object165_black_metallic_int_0.geometry} material={materials.black_metallic_int} position={[0, 2.227, 0.615]} />
            <mesh geometry={nodes.Object162_acnt_int_0.geometry} material={materials.acnt_int} position={[0, 2.227, 0.615]} />
            <mesh geometry={nodes.Object159_chrome_int_0.geometry} material={materials.chrome_int} position={[0, 2.227, 0.615]} />
            <mesh geometry={nodes['Object161_Material_#8_0'].geometry} material={materials.Material_8} position={[0, 2.227, 0.615]} />
            <mesh geometry={nodes.Object160_chrome_int_0.geometry} material={materials.chrome_int} position={[0, 2.227, 0.615]} />
            <mesh geometry={nodes.Object158_black_metallic_int_0.geometry} material={materials.black_metallic_int} position={[0, 2.227, 0.615]} />
            <mesh geometry={nodes.Object163_stitch_0.geometry} material={materials.stitch} position={[0, 2.227, 0.615]} />
            <mesh geometry={nodes.Object164_decal_int_0.geometry} material={materials.decal_int} position={[0, 2.227, 0.615]} />
            <mesh geometry={nodes.Object157_acnt_int_0.geometry} material={materials.acnt_int} position={[0, 2.227, 0.615]} />
            <mesh geometry={nodes.Object144_chrome_int_0.geometry} material={materials.chrome_int} position={[0, 2.227, 0.615]} />
            <mesh geometry={nodes.Object142_leather_123_All_0.geometry} material={materials.leather_123_All} position={[0, 2.227, 0.615]} />
            <mesh geometry={nodes.Object264_black_0.geometry} material={materials.black} position={[-0.067, 80.771, -6.062]} />
            <mesh geometry={nodes.Object141_black_int_0.geometry} material={materials.black_int} position={[0, 2.227, 0.615]} />
            <mesh geometry={nodes['Object267_Material_#20_0'].geometry} material={materials.Material_20} position={[-37.568, 17.953, 9.146]} />
            <mesh geometry={nodes.Object266_plastic_1_0.geometry} material={materials.plastic_1} position={[-37.568, 17.953, 9.146]} />
          </group>
          <group position={[0, 1.629, -0.984]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes['Object150_Material_#25_0'].geometry} material={materials.Material_25} position={[-0.002, -25.694, -14.878]} />
            <mesh geometry={nodes.TOYOTA_FORTUNER_IN_DMTAB_DATAB_DMTBB_DATBB_PMTAB_PATAB_ROOF_MES_plastic_egg_0.geometry} material={materials.plastic_egg} position={[-0.002, -25.694, -14.878]} />
            <mesh geometry={nodes.Object146_leather_egg_0.geometry} material={materials.leather_egg} position={[-0.002, -25.694, -14.878]} />
            <mesh geometry={nodes.Object147_plastic_egg_0.geometry} material={materials.plastic_egg} position={[-0.002, -25.694, -14.878]} />
            <mesh geometry={nodes.Object148_plastic_egg_0.geometry} material={materials.plastic_egg} position={[-0.002, -25.694, -14.878]} />
            <mesh geometry={nodes.Object149_decal_int_0.geometry} material={materials.decal_int} position={[-0.002, -25.694, -14.878]} />
            <mesh geometry={nodes.Object156_chrome_only_0.geometry} material={materials.chrome_only} position={[-0.002, -25.694, -14.878]} />
            <mesh geometry={nodes.Object152_seatbelt_0.geometry} material={materials.seatbelt} position={[-0.002, -25.694, -14.878]} />
            <mesh geometry={nodes.Object153_decal_int_0.geometry} material={materials.decal_int} position={[-0.002, -25.694, -14.878]} />
            <mesh geometry={nodes.Object154_plastic_egg_0.geometry} material={materials.plastic_egg} position={[-0.002, -25.694, -14.878]} />
            <mesh geometry={nodes.Object155_chrome_only_0.geometry} material={materials.chrome_only} position={[-0.002, -25.694, -14.878]} />
            <mesh geometry={nodes.TOYOTA_FORTUNER_IN_BODY_MESH_plastic_egg_0.geometry} material={materials.plastic_egg} position={[-0.434, -16.678, -55.793]} />
            <mesh geometry={nodes.Object151_glass_decal_0.geometry} material={materials.glass_decal} position={[-0.002, -25.694, -14.878]} />
          </group>
          <group position={[0, 1.049, -1.007]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.TOYOTA_FORTUNER_IN_SEAT_MECHANISM_MESH_seatbelt_0.geometry} material={materials.seatbelt} />
            <mesh geometry={nodes.Object254_plastic_1_0.geometry} material={materials.plastic_1} />
            <mesh geometry={nodes.Object255_plastic_1_0.geometry} material={materials.plastic_1} />
            <mesh geometry={nodes.Object256_plastic_1_0.geometry} material={materials.plastic_1} />
            <mesh geometry={nodes.Object257_plastic_egg_0.geometry} material={materials.plastic_egg} />
            <mesh geometry={nodes.Object263_decal_int_0.geometry} material={materials.decal_int} />
            <mesh geometry={nodes.Object262_r_tailight_0.geometry} material={materials.r_tailight} />
            <mesh geometry={nodes.Object260_plastic_egg_0.geometry} material={materials.plastic_egg} />
            <mesh geometry={nodes.Object261_chrome_only_0.geometry} material={materials.chrome_only} />
            <mesh geometry={nodes.Object258_black_metallic_int_0.geometry} material={materials.black_metallic_int} />
            <mesh geometry={nodes.Object259_chrome_int_0.geometry} material={materials.chrome_int} />
          </group>
          <group position={[0, 1.106, -0.999]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Object250_seat_leather_0.geometry} material={materials.seat_leather} />
            <mesh geometry={nodes['Object251_Material_#28_0'].geometry} material={materials.Material_28} />
            <mesh geometry={nodes['Object252_Material_#28_0'].geometry} material={materials.Material_28} />
            <mesh geometry={nodes['Object253_Material_#28_0'].geometry} material={materials.Material_28} />
            <mesh geometry={nodes.TOYOTA_FORTUNER_IN_DMTBB_DATBB_DMTAB_DATAB_PMTAB_PATAB_BLACKSEA_stitch_0.geometry} material={materials.stitch} />
          </group>
          <group position={[0.82, 0.958, -0.449]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.TOYOTA_FORTUNER_IN_DMTBB_DATBB_DATAB_RL_DOOR_BLACK_TRIM_MESH_stitch_0.geometry} material={materials.stitch} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh geometry={nodes.Object030_carpaint_0.geometry} material={materials.carpaint} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh geometry={nodes.Object062_black_0.geometry} material={materials.black} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh geometry={nodes['Object064_Material_#4_0'].geometry} material={materials.Material_4} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh geometry={nodes.Object066_chrome_0.geometry} material={materials.chrome} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh geometry={nodes.TOYOTA_FORTUNER_RL_DOOR_DMTAB_DATAB_DMTBB_DATBB_PMTAB_PATAB_MES_plastic_1_0.geometry} material={materials.plastic_1} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh geometry={nodes.Object248_decal_int_0.geometry} material={materials.decal_int} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh geometry={nodes.Object247_plastic_1_0.geometry} material={materials.plastic_1} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh geometry={nodes.Object245_r_tailight_0.geometry} material={materials.r_tailight} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh geometry={nodes.Object244_black_metallic_int_0.geometry} material={materials.black_metallic_int} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh geometry={nodes.Object241_decal_int_0.geometry} material={materials.decal_int} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh geometry={nodes.Object238_acnt_int_0.geometry} material={materials.acnt_int} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh geometry={nodes.Object239_windows_glass_0.geometry} material={materials.windows_glass} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh geometry={nodes.Object240_decal_int_0.geometry} material={materials.decal_int} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh geometry={nodes.Object242_chrome_int_0.geometry} material={materials.chrome_int} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh geometry={nodes.Object243_plastic_1_0.geometry} material={materials.plastic_1} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh geometry={nodes.Object246_black_metallic_int_0.geometry} material={materials.black_metallic_int} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh geometry={nodes.Object249_chrome_int_0.geometry} material={materials.chrome_int} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
          </group>
          <group position={[-0.744, 1.081, -0.953]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.TOYOTA_FORTUNER_IN_DMTBB_DATBB_DATAB_RR_DOOR_BLACK_TRIM_MESH_stitch_0.geometry} material={materials.stitch} position={[5.43, 0.073, -0.844]} />
            <mesh geometry={nodes.TOYOTA_FORTUNER_RR_DOOR_DMTAB_DATAB_DMTBB_DATBB_PMTAB_PATAB_MES_chrome_int_0.geometry} material={materials.chrome_int} />
            <mesh geometry={nodes.Object020_windows_glass_0.geometry} material={materials.windows_glass} position={[4.932, -0.995, 34.998]} />
            <mesh geometry={nodes.Object048_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Object050_chrome_0.geometry} material={materials.chrome} />
            <mesh geometry={nodes['Object049_Material_#4_0'].geometry} material={materials.Material_4} />
            <mesh geometry={nodes.Object032_carpaint_0.geometry} material={materials.carpaint} />
            <mesh geometry={nodes.Object226_acnt_int_0.geometry} material={materials.acnt_int} position={[5.43, 0.073, -0.844]} />
            <mesh geometry={nodes.Object227_plastic_1_0.geometry} material={materials.plastic_1} />
            <mesh geometry={nodes.Object228_decal_int_0.geometry} material={materials.decal_int} />
            <mesh geometry={nodes.Object229_decal_int_0.geometry} material={materials.decal_int} />
            <mesh geometry={nodes.Object230_black_metallic_int_0.geometry} material={materials.black_metallic_int} />
            <mesh geometry={nodes.Object231_decal_int_0.geometry} material={materials.decal_int} />
            <mesh geometry={nodes.Object232_plastic_1_0.geometry} material={materials.plastic_1} />
            <mesh geometry={nodes.Object233_plastic_1_0.geometry} material={materials.plastic_1} />
            <mesh geometry={nodes.Object234_r_tailight_0.geometry} material={materials.r_tailight} />
            <mesh geometry={nodes.Object235_chrome_int_0.geometry} material={materials.chrome_int} />
            <mesh geometry={nodes.Object236_black_metallic_int_0.geometry} material={materials.black_metallic_int} />
            <mesh geometry={nodes.Object237_plastic_1_0.geometry} material={materials.plastic_1} />
          </group>
          <group position={[0.795, 1.031, -0.036]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.TOYOTA_FORTUNER_EX_FEAT_L_DOOR_INDICATOR_MESH_indicator_signal_0.geometry} material={materials.indicator_signal} position={[17.359, -44.688, 25.726]} />
            <mesh geometry={nodes.TOYOTA_FORTUNER_FL_DOOR_DMTAB_DATAB_DMTBB_DATBB_PMTAB_PATAB_MES_plastic_1_0.geometry} material={materials.plastic_1} position={[0.889, -12.443, 4.396]} />
            <mesh geometry={nodes.TOYOTA_FORTUNER_IN_DMTBB_DATBB_DATAB_FL_DOOR_BLACK_TRIM_MESH_acnt_int_0.geometry} material={materials.acnt_int} position={[-11.343, -0.227, 0.155]} />
            <mesh geometry={nodes.Object029_carpaint_0.geometry} material={materials.carpaint} position={[0.889, -12.443, 4.396]} />
            <mesh geometry={nodes.Object061_black_0.geometry} material={materials.black} position={[0.889, -12.443, 4.396]} />
            <mesh geometry={nodes.Object063_carpaint_0.geometry} material={materials.carpaint} position={[0.889, -12.443, 4.396]} />
            <mesh geometry={nodes.Object065_chrome_0.geometry} material={materials.chrome} position={[0.889, -12.443, 4.396]} />
            <mesh geometry={nodes.Object116_plastic_1_0.geometry} material={materials.plastic_1} position={[0.889, -12.443, 4.396]} />
            <mesh geometry={nodes.Object212_black_metallic_int_0.geometry} material={materials.black_metallic_int} position={[0.889, -12.443, 4.396]} />
            <mesh geometry={nodes.Object213_decal_int_0.geometry} material={materials.decal_int} position={[0.889, -12.443, 4.396]} />
            <mesh geometry={nodes.Object214_black_metallic_int_0.geometry} material={materials.black_metallic_int} position={[0.889, -12.443, 4.396]} />
            <mesh geometry={nodes.Object215_chrome_only_0.geometry} material={materials.chrome_only} position={[0.889, -12.443, 4.396]} />
            <mesh geometry={nodes.Object216_windows_glass_0.geometry} material={materials.windows_glass} position={[0.889, -12.443, 4.396]} />
            <mesh geometry={nodes.Object217_plastic_1_0.geometry} material={materials.plastic_1} position={[0.889, -12.443, 4.396]} />
            <mesh geometry={nodes.Object218_decal_int_0.geometry} material={materials.decal_int} position={[0.889, -12.443, 4.396]} />
            <mesh geometry={nodes.Object219_chrome_int_0.geometry} material={materials.chrome_int} position={[0.889, -12.443, 4.396]} />
            <mesh geometry={nodes.Object220_decal_int_0.geometry} material={materials.decal_int} position={[0.889, -12.443, 4.396]} />
            <mesh geometry={nodes.Object221_r_tailight_0.geometry} material={materials.r_tailight} position={[0.889, -12.443, 4.396]} />
            <mesh geometry={nodes.Object222_plastic_1_0.geometry} material={materials.plastic_1} position={[0.889, -12.443, 4.396]} />
            <mesh geometry={nodes.Object223_chrome_int_0.geometry} material={materials.chrome_int} position={[0.889, -12.443, 4.396]} />
            <mesh geometry={nodes.Object224_black_second_int_0.geometry} material={materials.black_second_int} position={[0.889, -12.443, 4.396]} />
            <mesh geometry={nodes.Object225_stitch_0.geometry} material={materials.stitch} position={[-11.343, -0.227, 0.155]} />
          </group>
          <group position={[-0.684, 1.031, -0.036]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.TOYOTA_FORTUNER_IN_DMTBB_DATBB_DATAB_RF_DOOR_BLACK_TRIM_MESH_stitch_0.geometry} material={materials.stitch} />
            <mesh geometry={nodes.TOYOTA_FORTUNER_RF_DOOR_DMTAB_DATAB_DMTBB_DATBB_PMTAB_PATAB_MES_plastic_1_0.geometry} material={materials.plastic_1} position={[-12.233, -12.216, 4.241]} />
            <mesh geometry={nodes.Object019_windows_glass_0.geometry} material={materials.windows_glass} position={[-1.362, -7.046, 39.103]} />
            <mesh geometry={nodes.Object033_carpaint_0.geometry} material={materials.carpaint} position={[-12.233, -12.216, 4.241]} />
            <mesh geometry={nodes.Object046_indicator_signal_0.geometry} material={materials.indicator_signal} position={[-12.233, -12.216, 4.241]} />
            <mesh geometry={nodes.Object051_black_0.geometry} material={materials.black} position={[-12.233, -12.216, 4.241]} />
            <mesh geometry={nodes['Object052_Material_#4_0'].geometry} material={materials.Material_4} position={[-12.233, -12.216, 4.241]} />
            <mesh geometry={nodes.Object053_chrome_0.geometry} material={materials.chrome} position={[-12.233, -12.216, 4.241]} />
            <mesh geometry={nodes.Object209_decal_int_0.geometry} material={materials.decal_int} position={[-12.233, -12.216, 4.241]} />
            <mesh geometry={nodes.Object208_chrome_only_0.geometry} material={materials.chrome_only} position={[-12.233, -12.216, 4.241]} />
            <mesh geometry={nodes.Object197_acnt_int_0.geometry} material={materials.acnt_int} />
            <mesh geometry={nodes.Object198_black_metallic_int_0.geometry} material={materials.black_metallic_int} position={[-12.233, -12.216, 4.241]} />
            <mesh geometry={nodes.Object199_chrome_int_0.geometry} material={materials.chrome_int} position={[-12.233, -12.216, 4.241]} />
            <mesh geometry={nodes.Object200_black_metallic_int_0.geometry} material={materials.black_metallic_int} position={[-12.233, -12.216, 4.241]} />
            <mesh geometry={nodes.Object201_r_tailight_0.geometry} material={materials.r_tailight} position={[-12.233, -12.216, 4.241]} />
            <mesh geometry={nodes.Object202_chrome_int_0.geometry} material={materials.chrome_int} position={[-12.233, -12.216, 4.241]} />
            <mesh geometry={nodes.Object203_plastic_1_0.geometry} material={materials.plastic_1} position={[-12.233, -12.216, 4.241]} />
            <mesh geometry={nodes.Object204_plastic_1_0.geometry} material={materials.plastic_1} position={[-12.233, -12.216, 4.241]} />
            <mesh geometry={nodes.Object205_black_second_int_0.geometry} material={materials.black_second_int} position={[-12.233, -12.216, 4.241]} />
            <mesh geometry={nodes.Object206_decal_int_0.geometry} material={materials.decal_int} position={[-12.233, -12.216, 4.241]} />
            <mesh geometry={nodes.Object207_decal_int_0.geometry} material={materials.decal_int} position={[-12.233, -12.216, 4.241]} />
            <mesh geometry={nodes.Object211_plastic_1_0.geometry} material={materials.plastic_1} position={[-12.233, -12.216, 4.241]} />
          </group>
          <group position={[-0.757, 0.36, 1.118]}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
              <mesh geometry={nodes.Object089_tire_0.geometry} material={materials.tire} />
              <mesh geometry={nodes['Object090_Material_#4_0'].geometry} material={materials.Material_4} position={[0.042, 0, 0]} />
              <mesh geometry={nodes.Object091_rim_0.geometry} material={materials.material} position={[0.042, 0, 0]} />
              <mesh geometry={nodes.Object092_rim_0.geometry} material={materials.material} position={[0.042, 0, 0]} />
              <mesh geometry={nodes.Object093_chrome_0.geometry} material={materials.chrome} position={[0.042, 0, 0]} />
              <mesh geometry={nodes.Object094_black_0.geometry} material={materials.black} position={[0.042, 0, 0]} />
              <mesh geometry={nodes.Object095_tire_0.geometry} material={materials.tire} position={[0.042, 0, 0]} />
              <mesh geometry={nodes['Object096_Material_#18_0'].geometry} material={materials.Material_18} />
            </group>
          </group>
          <group position={[-0.762, 0.371, -1.576]}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
              <mesh geometry={nodes.Object086_black_0.geometry} material={materials.black} position={[0.042, 0, 0]} />
              <mesh geometry={nodes['Object088_Material_#18_0'].geometry} material={materials.Material_18} />
              <mesh geometry={nodes.Object084_rim_0.geometry} material={materials.material} position={[0.042, 0, 0]} />
              <mesh geometry={nodes['Object011_Material_#4_0'].geometry} material={materials.Material_4} position={[0.042, 0, 0]} />
              <mesh geometry={nodes.Object083_rim_0.geometry} material={materials.material} position={[0.042, 0, 0]} />
              <mesh geometry={nodes.Object085_chrome_0.geometry} material={materials.chrome} position={[0.042, 0, 0]} />
              <mesh geometry={nodes.Object087_tire_0.geometry} material={materials.tire} position={[0.042, 0, 0]} />
              <mesh geometry={nodes.Object010_tire_0.geometry} material={materials.tire} />
            </group>
          </group>
          <group position={[0.761, 0.371, -1.576]}>
            <group rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.01}>
              <mesh geometry={nodes.Object107_tire_0.geometry} material={materials.tire} />
              <mesh geometry={nodes['Object108_Material_#4_0'].geometry} material={materials.Material_4} position={[0.042, 0, 0]} />
              <mesh geometry={nodes.Object109_rim_0.geometry} material={materials.material} position={[0.042, 0, 0]} />
              <mesh geometry={nodes.Object110_rim_0.geometry} material={materials.material} position={[0.042, 0, 0]} />
              <mesh geometry={nodes.Object111_chrome_0.geometry} material={materials.chrome} position={[0.042, 0, 0]} />
              <mesh geometry={nodes.Object112_black_0.geometry} material={materials.black} position={[0.042, 0, 0]} />
              <mesh geometry={nodes.Object113_tire_0.geometry} material={materials.tire} position={[0.042, 0, 0]} />
              <mesh geometry={nodes['Object114_Material_#18_0'].geometry} material={materials.Material_18} />
            </group>
          </group>
          <group position={[0.755, 0.364, 1.118]}>
            <group rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.01}>
              <mesh geometry={nodes.Object099_tire_0.geometry} material={materials.tire} />
              <mesh geometry={nodes['Object100_Material_#4_0'].geometry} material={materials.Material_4} position={[0.042, 0, 0]} />
              <mesh geometry={nodes.Object101_rim_0.geometry} material={materials.material} position={[0.042, 0, 0]} />
              <mesh geometry={nodes.Object102_rim_0.geometry} material={materials.material} position={[0.042, 0, 0]} />
              <mesh geometry={nodes.Object103_chrome_0.geometry} material={materials.chrome} position={[0.042, 0, 0]} />
              <mesh geometry={nodes.Object104_black_0.geometry} material={materials.black} position={[0.042, 0, 0]} />
              <mesh geometry={nodes.Object105_tire_0.geometry} material={materials.tire} position={[0.042, 0, 0]} />
              <mesh geometry={nodes['Object106_Material_#18_0'].geometry} material={materials.Material_18} />
            </group>
          </group>
          <group position={[0.755, 0.364, 1.118]}>
            <mesh geometry={nodes.Object098_rim_0.geometry} material={materials.material} position={[-0.563, -0.84, 1.1]} rotation={[Math.PI, 1.388, -Math.PI]} scale={0.01} />
          </group>
          <group position={[-0.757, 0.36, 1.118]}>
            <mesh geometry={nodes.Object009_rim_0.geometry} material={materials.material} position={[-0.026, 0.015, 0.137]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          </group>
          <group position={[-0.367, 1.19, 0.187]} rotation={[0.415, 0, 0]} scale={0.158}>
            <group position={[0, 0.032, 0.202]} rotation={[-1.985, 0, 0]} scale={0.062}>
              <mesh geometry={nodes.TOYOTA_FORTUNER_IN_DMTBB_DMTAB_PMTAB_STEERING_COLUMN_MESH_plastic_1_0.geometry} material={materials.plastic_1} position={[37.5, -191.815, -169.23]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Object133_decal_int_0.geometry} material={materials.decal_int} position={[37.5, -191.815, -169.23]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Object014_decal_int_0.geometry} material={materials.decal_int} position={[37.5, -191.815, -169.23]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Object015_plastic_1_0.geometry} material={materials.plastic_1} position={[37.5, -191.815, -169.23]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              <mesh geometry={nodes['Object016_Material_#20_0'].geometry} material={materials.Material_20} position={[0, 3.197, 0.847]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Object137_black_int_0.geometry} material={materials.black_int} position={[37.5, -191.815, -169.23]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Object138_chrome_int_0.geometry} material={materials.chrome_int} position={[37.5, -191.815, -169.23]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Object132_plastic_1_0.geometry} material={materials.plastic_1} position={[37.5, -191.815, -169.23]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Object136_black_int_0.geometry} material={materials.black_int} position={[37.5, -191.815, -169.23]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Object134_plastic_1_0.geometry} material={materials.plastic_1} position={[37.5, -191.815, -169.23]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Object135_leather_123_All_0.geometry} material={materials.leather_123_All} position={[37.5, -191.815, -169.23]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Object139_black_int_0.geometry} material={materials.black_int} position={[37.5, -191.815, -169.23]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Object017_stitch_0.geometry} material={materials.stitch} position={[37.5, -191.815, -169.23]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              <mesh geometry={nodes.Object265_black_0.geometry} material={materials.black} position={[-0.018, -1.169, -4.935]} />
              <mesh geometry={nodes.Object140_leather_0.geometry} material={materials.leather} position={[37.5, -191.815, -169.23]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            </group>
          </group>
          <group position={[0, 1.697, -2.054]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object070_black_0.geometry} material={materials.black} position={[0, 0.269, -0.366]} scale={0.01} />
            <mesh geometry={nodes.Object075_chrome_0.geometry} material={materials.chrome} position={[0, 0.362, -0.607]} scale={0.01} />
            <mesh geometry={nodes.Object060_windows_glass_0.geometry} material={materials.windows_glass} position={[0, 0.25, -0.242]} scale={0.01} />
            <mesh geometry={nodes.Object171_o_0.geometry} material={materials.material_34} position={[0, 0.276, -0.242]} scale={0.01} />
            <mesh geometry={nodes.Object170_r_glass_0.geometry} material={materials.r_glass} position={[0, 0.308, -0.053]} scale={0.01} />
            <mesh geometry={nodes.Object169_black_0.geometry} material={materials.black} position={[0.069, 0.42, -0.54]} scale={0.01} />
            <mesh geometry={nodes.Object172_leather_egg_0.geometry} material={materials.leather_egg} position={[0, 0.2, -0.21]} scale={0.01} />
            <mesh geometry={nodes.Object115_chrome_0.geometry} material={materials.chrome} position={[0, 0.393, -0.51]} scale={0.01} />
            <mesh geometry={nodes.Object168_black_int_0.geometry} material={materials.black_int} position={[0, 0.233, -0.313]} scale={0.01} />
            <mesh geometry={nodes.Object074_black_0.geometry} material={materials.black} position={[0, 0.403, -0.53]} scale={0.01} />
            <mesh geometry={nodes.Object173_decal_int_0.geometry} material={materials.decal_int} position={[0.004, 0.366, -0.909]} scale={0.01} />
            <mesh geometry={nodes.Object069_r_tailight_0.geometry} material={materials.r_tailight} position={[0, 0.405, -0.536]} scale={0.01} />
            <mesh geometry={nodes.Object174_plastic_1_0.geometry} material={materials.plastic_1} position={[0, 0.321, -0.647]} scale={0.01} />
            <mesh geometry={nodes.Object044_black_int_0.geometry} material={materials.black_int} position={[0, 0.25, -0.496]} scale={0.01} />
            <mesh geometry={nodes.Object175_decal_int_0.geometry} material={materials.decal_int} position={[0.007, 0.378, -0.388]} scale={0.01} />
            <mesh geometry={nodes['Object002_Material_#8_0'].geometry} material={materials.Material_8} position={[0, 0.408, -0.56]} scale={0.01} />
            <mesh geometry={nodes.TOYOTA_FORTUNER_EX_BOOTDOOR_DMTAB_DATAB_DMTBB_DATBB_PMTAB_PATAB_carpaint_0.geometry} material={materials.carpaint} position={[0, 0.296, -0.526]} scale={0.01} />
            <mesh geometry={nodes.Object031_carpaint_0.geometry} material={materials.carpaint} position={[0, 0.253, -0.487]} scale={0.01} />
          </group>
          <group position={[-0.277, 1.187, 0.481]} rotation={[0.382, 0, 0]} scale={0.02}>
            <mesh geometry={nodes['Object126_Material_#20_0'].geometry} material={materials.Material_20} rotation={[-1.953, 0, 0]} scale={0.123} />
            <mesh geometry={nodes.Object127_indicator_arrow_0.geometry} material={materials.indicator_arrow} position={[-4.455, -3.602, -4.697]} rotation={[-1.953, 0, 0]} scale={0.484} />
          </group>
          <group position={[-0.277, 1.167, 0.472]} rotation={[0.463, 0, 0]} scale={0.02}>
            <mesh geometry={nodes.Object283_indicator_arrow_0.geometry} material={materials.indicator_arrow} position={[-4.456, -2.905, -4.424]} rotation={[-2.034, 0, 0]} scale={0.484} />
            <mesh geometry={nodes['Object280_Material_#20_0'].geometry} material={materials.Material_20} rotation={[-2.034, 0, 0]} scale={49.355} />
          </group>
          <group position={[-0.458, 1.187, 0.481]} rotation={[0.367, 0, 0.04]} scale={0.02}>
            <mesh geometry={nodes['Object278_Material_#20_0'].geometry} material={materials.Material_20} position={[-0.022, -0.005, -0.013]} rotation={[-1.938, 0, 0]} scale={49.355} />
            <mesh geometry={nodes.Object282_indicator_arrow_0.geometry} material={materials.indicator_arrow} position={[4.476, -3.533, -4.75]} rotation={[-1.938, 0, 0]} scale={0.484} />
          </group>
          <group position={[-0.458, 1.167, 0.472]} rotation={[0.463, 0, 0]} scale={0.02}>
            <mesh geometry={nodes.Object281_indicator_arrow_0.geometry} material={materials.indicator_arrow} position={[4.475, -2.905, -4.424]} rotation={[-2.034, 0, 0]} scale={0.484} />
            <mesh geometry={nodes['Object279_Material_#20_0'].geometry} material={materials.Material_20} position={[0.003, -0.027, 0.009]} rotation={[-2.034, 0, 0]} scale={49.355} />
          </group>
          <group position={[-0.075, 1.224, 0.88]} rotation={[-0.973, 0, 0]}>
            <group position={[0.532, 0.095, -0.014]}>
              <mesh geometry={nodes['Object286_Material_#4_0'].geometry} material={materials.Material_4} position={[0.005, 0.004, -0.017]} rotation={[-0.598, 0, 0]} />
              <mesh geometry={nodes.Object288_black_0.geometry} material={materials.black} position={[0.005, -0.001, -0.026]} rotation={[-0.598, 0, 0]} scale={0.01} />
            </group>
            <mesh geometry={nodes['Object284_Material_#4_0'].geometry} material={materials.Material_4} position={[0.264, 0.039, -0.019]} rotation={[-0.598, 0, 0]} />
          </group>
          <group position={[-0.565, 1.195, 0.861]} rotation={[-0.973, 0, 0]}>
            <group position={[0.517, 0.073, 0.039]}>
              <mesh geometry={nodes['Object287_Material_#4_0'].geometry} material={materials.Material_4} position={[0.005, 0, -0.018]} rotation={[-0.598, 0, 0]} />
              <mesh geometry={nodes.Object289_black_0.geometry} material={materials.black} position={[0.005, -0.002, -0.028]} rotation={[-0.598, 0, 0]} scale={0.01} />
            </group>
            <mesh geometry={nodes['Object285_Material_#4_0'].geometry} material={materials.Material_4} position={[0.257, 0.028, 0.007]} rotation={[-0.598, 0, 0]} />
          </group>
          <group position={[0.727, 1.171, -2.387]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Turn_signal_L_4_ind_tailighjt_0.geometry} material={materials.ind_tailighjt} position={[-0.727, -4.484, -1.647]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.01} />
          </group>
          <group position={[0.639, 1.168, -2.424]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Turn_signal_L_3_ind_tailighjt_0.geometry} material={materials.ind_tailighjt} position={[-0.639, -0.354, 0.545]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.01} />
          </group>
          <group position={[0.577, 1.166, -2.448]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Turn_signal_L_2_ind_tailighjt_0.geometry} material={materials.ind_tailighjt} position={[-0.577, -0.378, 0.547]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.01} />
          </group>
          <group position={[0.517, 1.164, -2.468]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Turn_signal_L_1_ind_tailighjt_0.geometry} material={materials.ind_tailighjt} position={[-0.517, -0.398, 0.549]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.01} />
          </group>
          <group position={[0.822, 1.171, -2.209]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Turn_signal_L_6_ind_tailighjt_0.geometry} material={materials.ind_tailighjt} position={[-0.821, -4.307, -1.647]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.01} />
          </group>
          <group position={[0.785, 1.172, -2.322]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Turn_signal_L_5_ind_tailighjt_0.geometry} material={materials.ind_tailighjt} position={[-0.785, -4.42, -1.648]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.01} />
          </group>
          <group position={[0.463, 1.163, -2.483]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Turn_signal_L_0_ind_tailighjt_0.geometry} material={materials.ind_tailighjt} position={[-0.463, -0.413, 0.549]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.01} />
          </group>
          <mesh geometry={nodes['Object035_Material_#4_0'].geometry} material={materials.Material_4} position={[0, 1.006, -0.25]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object034_black_0.geometry} material={materials.black} position={[0, 1.006, -0.25]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object023_carpaint_0.geometry} material={materials.carpaint} position={[0, 1.044, -0.337]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object270_chrome_0.geometry} material={materials.chrome} position={[0, 0.871, -0.264]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes['Object269_Material_#4_0'].geometry} material={materials.Material_4} position={[0, 0.871, -0.264]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object196_plastic_1_0.geometry} material={materials.plastic_1} position={[0, 0.674, -0.769]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object177_black_int_0.geometry} material={materials.black_int} position={[0, 1.006, -0.25]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object176_black_int_0.geometry} material={materials.black_int} position={[0, 1.006, -0.25]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object121_indicator_signal_0.geometry} material={materials.indicator_signal} position={[0, 0.871, -0.264]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes['Object120_Material_#8_0'].geometry} material={materials.Material_8} position={[0, 0.871, -0.264]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes['Object119_Material_#22_0'].geometry} material={materials.Material_22} position={[-0.004, 1.083, -0.821]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object118_decal_int_0.geometry} material={materials.decal_int} position={[-0.004, 1.083, -0.821]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object117_plastic_1_0.geometry} material={materials.plastic_1} position={[-0.004, 1.083, -0.821]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object082_r_tailight_0.geometry} material={materials.r_tailight} position={[0, 0.871, -0.264]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object079_chrome_0.geometry} material={materials.chrome} position={[0, 0.871, -0.264]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object078_black_0.geometry} material={materials.black} position={[0, 0.871, -0.264]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object076_black_0.geometry} material={materials.black} position={[0, 0.871, -0.264]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object068_carpaint_0.geometry} material={materials.carpaint} position={[0, 1.044, -0.337]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object059_black_0.geometry} material={materials.black} position={[0, 0.871, -0.264]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object058_chrome_0.geometry} material={materials.chrome} position={[0, 0.871, -0.264]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes['Object047_Material_#8_0'].geometry} material={materials.Material_8} position={[0, 0.871, -0.264]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object045_carpaint_0.geometry} material={materials.carpaint} position={[0, 1.006, -0.25]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object043_plastic_1_0.geometry} material={materials.plastic_1} position={[0, 1.006, -0.25]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object042_black_0.geometry} material={materials.black} position={[0, 1.006, -0.25]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object041_grey_0.geometry} material={materials.grey} position={[0, 1.006, -0.25]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object040_windows_glass_0.geometry} material={materials.windows_glass} position={[0, 1.006, -0.25]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object039_black_0.geometry} material={materials.black} position={[0, 1.006, -0.25]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object038_chrome_0.geometry} material={materials.chrome} position={[0, 0.527, 1.98]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object037_chrome_0.geometry} material={materials.chrome} position={[0, 1.006, -0.25]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object036_chrome_0.geometry} material={materials.chrome} position={[0, 1.006, -0.25]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object028_carpaint_0.geometry} material={materials.carpaint} position={[0, 1.044, -0.337]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object027_carpaint_0.geometry} material={materials.carpaint} position={[0, 0.688, 1.76]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object026_carpaint_0.geometry} material={materials.carpaint} position={[0, 1.146, 1.405]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object025_carpaint_0.geometry} material={materials.carpaint} position={[0, 0.855, 1.076]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object022_black_0.geometry} material={materials.black} position={[0, 1.108, -0.158]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.Object012_windows_glass_0.geometry} material={materials.windows_glass} position={[0, 1.427, 0.487]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.TOYOTA_FORTUNER_IN_DMTBB_DMTAB_PMTAB_FLOOR_MESH_black_second_int_0.geometry} material={materials.black_second_int} position={[0, 0.674, -0.769]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.TOYOTA_FORTUNER_FEAT_GRILLE_MESH_grey_0.geometry} material={materials.grey} position={[0, 0.912, 2.02]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.TOYOTA_FORTUNER_EX_LIGHTS_DMTAB_DATAB_DMTBB_DATBB_PMTAB_PATAB_M_r_glass_0.geometry} material={materials.r_glass} position={[0, 0.871, -0.264]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.TOYOTA_FORTUNER_EX_CARPAINT_DMTAB_DATAB_DMTBB_DATBB_PMTAB_PATAB_decal_int_0.geometry} material={materials.decal_int} position={[0, 1.006, -0.25]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes.black_matt_02_black_matt_0.geometry} material={materials.black_matt} position={[0, 0.616, -0.369]} rotation={[-1.583, 0, 0]} scale={[0.01, 0.009, 0.009]} />
          <mesh geometry={nodes.Turn_signal_R_3_ind_tailighjt_0.geometry} material={materials.ind_tailighjt} position={[-0.639, 1.168, -2.424]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Turn_signal_R_2_ind_tailighjt_0.geometry} material={materials.ind_tailighjt} position={[-0.578, 1.166, -2.448]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Turn_signal_R_1_ind_tailighjt_0.geometry} material={materials.ind_tailighjt} position={[-0.518, 1.164, -2.468]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Turn_signal_R_0_ind_tailighjt_0.geometry} material={materials.ind_tailighjt} position={[-0.463, 1.163, -2.483]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Turn_signal_R_4_ind_tailighjt_0.geometry} material={materials.ind_tailighjt} position={[-0.726, 1.171, -2.387]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Turn_signal_R_5_ind_tailighjt_0.geometry} material={materials.ind_tailighjt} position={[-0.784, 1.172, -2.323]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Turn_signal_R_6_ind_tailighjt_0.geometry} material={materials.ind_tailighjt} position={[-0.821, 1.171, -2.21]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['Plane001_Material_#166_0'].geometry} material={materials.Material_166} position={[-0.327, 1.226, 0.504]} rotation={[-2.591, 0, Math.PI]} scale={[0.852, 0.645, 0.873]} />
          <mesh geometry={nodes['Object290_Material_#166_0'].geometry} material={materials.Material_166} position={[-0.327, 1.226, 0.504]} rotation={[-2.591, 0, Math.PI]} scale={[0.852, 0.645, 0.873]} />
          <mesh geometry={nodes.Object291_indicator_signal_0.geometry} material={materials.indicator_signal} position={[0, 0.871, -0.264]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
          <mesh geometry={nodes['Object292_Material_#167_0'].geometry} material={materials.Material_167} position={[0.001, 1.071, 0.519]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../assets/Fortuner/scene.gltf')
